// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, SongSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  SongSchema = new Schema({
    name: String
  });

  module.exports = mongoose.model('Song', SongSchema);

}).call(this);

//# sourceMappingURL=song.map
